// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeabrYEGe79S7xGJJ9gVRwcLVeusvizLU',
    appId: '1:975574887542:web:5af84cc36fc04748c0c357',
    messagingSenderId: '975574887542',
    projectId: 'flash-chat-69b87',
    authDomain: 'flash-chat-69b87.firebaseapp.com',
    storageBucket: 'flash-chat-69b87.appspot.com',
    measurementId: 'G-7PQZXVH3EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjiJztxDxUp1Aewhb0XnYiR0dX5ryiCk',
    appId: '1:975574887542:android:a146317e722f6674c0c357',
    messagingSenderId: '975574887542',
    projectId: 'flash-chat-69b87',
    storageBucket: 'flash-chat-69b87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7clEHH_6QDdTlmilvTY5OxshptBNxec',
    appId: '1:975574887542:ios:53873c7a42c24481c0c357',
    messagingSenderId: '975574887542',
    projectId: 'flash-chat-69b87',
    storageBucket: 'flash-chat-69b87.appspot.com',
    iosClientId: '975574887542-bfdo97qmt8rfh90nged44rqf9u22a2e3.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7clEHH_6QDdTlmilvTY5OxshptBNxec',
    appId: '1:975574887542:ios:53873c7a42c24481c0c357',
    messagingSenderId: '975574887542',
    projectId: 'flash-chat-69b87',
    storageBucket: 'flash-chat-69b87.appspot.com',
    iosClientId: '975574887542-bfdo97qmt8rfh90nged44rqf9u22a2e3.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat',
  );
}
